apiVersion: v1
data:
  BACKEND_PORT: "8000"
  DATABASE_URL: postgresql+asyncpg://testuser:VolCap3D1234!@postgres:5432/testdb
  DB_HOST: postgres
  DB_NAME: testdb
  DB_PASSWORD: VolCap3D1234!
  DB_PORT: "5432"
  DB_USERNAME: testuser
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend-platform--env
  name: platform--env
