services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: VolCap3D1234!
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  falco:
    image: falcosecurity/falco:latest
    container_name: falco
    privileged: true
    pid: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /dev:/host/dev
      - /lib/modules:/host/lib/modules:ro
      - /boot:/host/boot:ro
      - /usr:/host/usr:ro
    restart: unless-stopped

  falcosidekick:
      image: falcosecurity/falcosidekick:latest
      container_name: falcosidekick
      ports:
        - "2801:2801"
      environment:
        - DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/1506270977850343444/fgM_FNrCiQzZBNXpexVIYa-M-fRUwtIlHbMrd18ZsUZJRUQzCeo2hIuTVy9aHfoP_MUO
      restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: john@doe.com
      PGADMIN_DEFAULT_PASSWORD: VolCap3D1234!
    ports:
      - "8080:80"
volumes:
  postgres_data:
    driver: local

