apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      environment: dev

namespace: kind-gitops-cluster  # Verander dit naar jouw namespace