apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml --out k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: falcosidekick
  name: falcosidekick
spec:
  ports:
    - name: "2801"
      port: 2801
      targetPort: 2801
  selector:
    io.kompose.service: falcosidekick
